// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_second.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class SecondFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2-3xBriAxVwVQ2yuqbf1um18OdRaYCE',
    appId: '1:641880302628:web:5943773234b062666ea4b1',
    messagingSenderId: '641880302628',
    projectId: 'sec-fire',
    authDomain: 'sec-fire.firebaseapp.com',
    storageBucket: 'sec-fire.firebasestorage.app',
    measurementId: 'G-74ZT849SEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0_1R5faSE0BGU1SffrdS35ddb1X4HyI',
    appId: '1:641880302628:android:03ca96b048d9ee626ea4b1',
    messagingSenderId: '641880302628',
    projectId: 'sec-fire',
    storageBucket: 'sec-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN10zhSLtGSQFe5a8TH7Sp9IbEeZn0Wb4',
    appId: '1:641880302628:ios:40c0d9427bce1b726ea4b1',
    messagingSenderId: '641880302628',
    projectId: 'sec-fire',
    storageBucket: 'sec-fire.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN10zhSLtGSQFe5a8TH7Sp9IbEeZn0Wb4',
    appId: '1:641880302628:ios:40c0d9427bce1b726ea4b1',
    messagingSenderId: '641880302628',
    projectId: 'sec-fire',
    storageBucket: 'sec-fire.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ2-3xBriAxVwVQ2yuqbf1um18OdRaYCE',
    appId: '1:641880302628:web:7a568f36778e9c8e6ea4b1',
    messagingSenderId: '641880302628',
    projectId: 'sec-fire',
    authDomain: 'sec-fire.firebaseapp.com',
    storageBucket: 'sec-fire.firebasestorage.app',
    measurementId: 'G-LBPDR1VBEZ',
  );
}
