// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86zy9vuCg85IKFWz4xm7DIITi0k5qN4U',
    appId: '1:9673785582:web:c1c77b71decf985f4b73ff',
    messagingSenderId: '9673785582',
    projectId: 'primary-fire',
    authDomain: 'primary-fire.firebaseapp.com',
    storageBucket: 'primary-fire.firebasestorage.app',
    measurementId: 'G-TTNNW86JZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQZWUhBAuHpoMUSsictBLVahE_gYZttM',
    appId: '1:9673785582:android:ca53df386782ca694b73ff',
    messagingSenderId: '9673785582',
    projectId: 'primary-fire',
    storageBucket: 'primary-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKIYhFkg-wQYy899qye5mpReATe9U9a8',
    appId: '1:9673785582:ios:da77f891875813244b73ff',
    messagingSenderId: '9673785582',
    projectId: 'primary-fire',
    storageBucket: 'primary-fire.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSKIYhFkg-wQYy899qye5mpReATe9U9a8',
    appId: '1:9673785582:ios:da77f891875813244b73ff',
    messagingSenderId: '9673785582',
    projectId: 'primary-fire',
    storageBucket: 'primary-fire.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB86zy9vuCg85IKFWz4xm7DIITi0k5qN4U',
    appId: '1:9673785582:web:d381378d9b1b186e4b73ff',
    messagingSenderId: '9673785582',
    projectId: 'primary-fire',
    authDomain: 'primary-fire.firebaseapp.com',
    storageBucket: 'primary-fire.firebasestorage.app',
    measurementId: 'G-HSFK6BDRC1',
  );
}
